/**
 * Bone SVG ID Constants
 * 
 * Master list of valid bone/anatomical structure IDs that correspond to SVG paths.
 * Used throughout the application for structure references and validation.
 */

export const EXISTING_BONES_SVG = [
  "foot-left",
  "tarsals-left",
  "metatarsals-left",
  "phalanges-left",
  "foot-right",
  "tarsals-right",
  "metatarsals-right",
  "phalanges-right",
  "femur-right",
  "femur-left",
  "fibula-left",
  "fibula-right",
  "tibia",
  "tibia-left",
  "tibia-right",
  "patella-left",
  "patella-right",
  "pelvis",
  "pelvic-girdle",
  "sacrum",
  "coccyx",
  "lumbar-vertebrae",
  "ribcage",
  "thoracic-vertebrae",
  "cervical-vertebrae",
  "knee-joint-left",
  "knee-joint-right",
  "hip-joint-left",
  "hip-joint-right",
  "sternum",
  "manubrium",
  "skull",
  "mandible",
  "teeth",
  "cranium",
  "scapula",
  "scapular-left",
  "scapula-right",
  "clavicle-left",
  "clavicle-right",
  "humerus-left",
  "humerus-right",
  "radius-left",
  "radius-right",
  "ulna-left",
  "ulna-right",
  "hand-left",
  "hand-right",
  "carpals-left",
  "carpals-right",
  "metacarpals-left",
  "metacarpals-right",
  "phalanges-left",
  "phalanges-right",
  "phalanges-f-left",
  "phalanges-f-right",
] as const;
